### ISSUE TITLE
Need to handle exceptions

### ISSUE THREAD

**Issue by karimzakir02** [CSC207-UofT/course-project-sports-agents#22]
Hey guys!

Just wanted to point out that we need to handle exceptions better. Currently, we don't really have any good way of handling exceptions. We catch them in certain spots, but otherwise, not much.

I think we can use a similar system to JShell. I will start implementing this system soon. Let me know if you have any other ideas in this thread!

**Comment by isaiahah** [comment]
Where should we store the exceptions? Do we want one large package of exceptions, or should each package store its own exceptions?

**Comment by karimzakir02** [comment]
I think we will have a separate package with exceptions. In case we add any other constants later, we will also store the constants there as well. Gives us more flexibility down the line.

**Comment by karimzakir02** [comment]
I will start implementing it, so that it is ready for Phase 1 in the exceptions branch

**Comment by karimzakir02** [comment]
I've added a pull request, which adds exception handling and a constants package. Check it out and let me know if I missed anything
